version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres_db_data:
